export const strategyDefinitions = [
  { id: 'insight', label: 'Personal insight', type: 'insight', description: 'Add a useful distinction, observation, or framework that advances the post’s idea.', when: 'Use when you can add a perspective the original post does not already cover.', example: 'The important distinction may be between reducing steps and removing the handoff that interrupts the work.' },
  { id: 'question', label: 'Thoughtful question', type: 'question', description: 'Invite a specific next layer of context without putting the burden of the conversation on a vague question.', when: 'Use when the author is active or the post leaves an assumption worth exploring.', example: 'How did you separate the first-value problem from setup friction in those sessions?' },
  { id: 'experience', label: 'Relevant experience', type: 'experience', description: 'Connect the discussion to a concrete lesson from work you have actually done.', when: 'Use when your experience provides evidence or a practical caution, not just a credential.', example: 'We saw a similar pattern in support: carrying context across teams mattered more than speeding up the first reply.' },
  { id: 'educational', label: 'Educational', type: 'educational', description: 'Explain a concept or evaluation lens that readers can apply to their own decisions.', when: 'Use when a small framework or definition makes the topic easier to act on.', example: 'We track correction time alongside task success, since a good benchmark can hide a difficult recovery path.' },
  { id: 'contrarian', label: 'Respectful counterpoint', type: 'contrarian', description: 'Qualify a broad claim with a relevant tradeoff or adjacent signal.', when: 'Use when the conversation is one-sided and you can add nuance without manufacturing disagreement.', example: 'The request can be a symptom and still reveal urgency; tracking the workaround can help distinguish the two.' },
  { id: 'supporting', label: 'Supporting', type: 'supporting', description: 'Reinforce a useful point with specific evidence, an example, or a clear implication.', when: 'Use when you can contribute more than agreement and make the original insight easier to remember.', example: 'That matches what we saw: the repeat behavior appeared before the larger reach lift.' },
] as const;

export const strategyFilters = ['All strategies', 'Strongest replies', 'Needs more data'] as const;